[project]
name = "route-check"
version = "0.1.0"
description = ""
authors = [
  { name = "", email = "" }
]
dependencies = [
  "ortools"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta" 